# Generated by Django 3.2.5 on 2021-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20210826_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='obs',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cor',
            field=models.CharField(choices=[('#ffffff', 'Branco'), ('#ffebcd', 'Creme'), ('#87cefa', 'Azul Claro'), ('#c8a2c8', 'Lilás'), ('#e4f1cb', 'Verde Claro'), ('#dedede', 'Cinza')], default='#ffffff', max_length=30),
        ),
    ]
