# Generated by Django 3.2.5 on 2022-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_auto_20220831_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cor',
            field=models.CharField(blank=True, default='#0a68cc', max_length=30),
        ),
    ]
