# Generated by Django 3.2.4 on 2021-07-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('peso', models.FloatField(blank=True, default=0, null=True)),
                ('unid_medida', models.CharField(choices=[('UNID', 'Unidade'), ('M', 'Metros'), ('M2', 'Metros2'), ('M3', 'Metros3'), ('CX', 'Caixa'), ('CJ', 'Conjunto'), ('PCT', 'Pacote'), ('PÇ', 'Peça'), ('TON', 'Tonelada'), ('LT', 'Litros'), ('BD', 'Balde'), ('QTD', 'Quantidade')], default='UNID', max_length=50)),
                ('qtd_minima', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='preço')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('categoria', models.ForeignKey(blank=True, default='Sem Descrição', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, default='Sem Fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saída')], default='1', max_length=50)),
                ('qtd', models.FloatField(blank=True, default=0, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='estoque.item')),
            ],
        ),
    ]
