# Generated by Django 3.2.5 on 2021-08-20 14:45

from django.db import migrations, models
import estoque.models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210820_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estoque/', validators=[estoque.models.Item.validate_image]),
        ),
    ]
