# Generated by Django 3.2.5 on 2022-08-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0005_alter_item_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('adicionado', models.BooleanField(default=False)),
                ('data_inclusao', models.DateField(default='17/08/2022 - 15:39')),
                ('log', models.CharField(blank=True, max_length=300, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
