# Generated by Django 3.2.5 on 2022-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_logmovimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmovimentacao',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
