# Generated by Django 3.2.5 on 2022-08-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_itensselecionados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensselecionados',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.estoque', unique=True),
        ),
    ]
