# Generated by Django 3.2.5 on 2022-08-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_itensselecionados_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensselecionados',
            name='estoque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.estoque'),
        ),
    ]
