# Generated by Django 3.2.5 on 2023-07-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_itensselecionados_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmovimentacao',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.item'),
        ),
    ]
