# Generated by Django 3.2.5 on 2023-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_logmovimentacao_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmovimentacao',
            name='item',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
