# Generated by Django 4.2.4 on 2023-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_item_estocado_alter_item_unid_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qtd_minima',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
