# Generated by Django 3.2.4 on 2021-07-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('estoque', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default='08/07/2021', null=True)),
                ('almoxarife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarife_req', to='funcionarios.funcionario')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.local')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_req', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, to='estoque.Item')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicao.requisicao')),
            ],
        ),
    ]
