# Generated by Django 3.2.4 on 2022-08-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_auto_20210721_1202'),
        ('estoque', '0010_alter_itensselecionados_estoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0003_obra_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almoxarife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_req_temp', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('almoxarife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_req', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicaoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque')),
                ('requisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisicao.requisicaotemp')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque')),
                ('requisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisicao.requisicao')),
            ],
        ),
    ]
