# Generated by Django 3.2.4 on 2022-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaotemp',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
