# Generated by Django 3.2.5 on 2021-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0005_alter_requisicao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateField(blank=True, default='21/07/2021', null=True),
        ),
    ]
