# Generated by Django 3.2.5 on 2022-08-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_itensselecionados_estoque'),
        ('funcionarios', '0003_auto_20210721_1202'),
        ('obras', '0003_obra_fiscal'),
        ('requisicao', '0020_alter_requisicao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateField(blank=True, default='22/08/2022', null=True),
        ),
        migrations.CreateModel(
            name='RequisicaoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default='22/08/2022', null=True)),
                ('almoxarife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarife_req_temp', to='funcionarios.funcionario')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.local')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_req_temp', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicaoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, to='estoque.Item')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicao.requisicaotemp')),
            ],
        ),
    ]
