# Generated by Django 3.2.5 on 2022-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0021_auto_20220822_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
