# Generated by Django 3.2.5 on 2022-08-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0022_auto_20220822_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequisicao',
            name='requisicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisicao.requisicao'),
        ),
    ]
