# Generated by Django 3.2.5 on 2022-08-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_fiscal'),
        ('funcionarios', '0003_auto_20210721_1202'),
        ('requisicao', '0023_alter_itemrequisicao_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaotemp',
            name='almoxarife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarife_req_temp', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.local'),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_req_temp', to='funcionarios.funcionario'),
        ),
    ]
