# Generated by Django 3.2.5 on 2022-08-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_fiscal'),
        ('estoque', '0010_alter_itensselecionados_estoque'),
        ('requisicao', '0025_auto_20220825_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequisicao',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque'),
        ),
        migrations.AlterField(
            model_name='itemrequisicao',
            name='requisicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisicao.requisicao'),
        ),
        migrations.RemoveField(
            model_name='itemrequisicaotemp',
            name='item',
        ),
        migrations.AddField(
            model_name='itemrequisicaotemp',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque'),
        ),
        migrations.AlterField(
            model_name='itemrequisicaotemp',
            name='requisicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisicao.requisicaotemp'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local'),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local'),
        ),
    ]
