# Generated by Django 3.2.5 on 2022-08-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisicao', '0026_auto_20220825_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaotemp',
            name='data',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='almoxarife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaotemp',
            name='almoxarife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
