# Generated by Django 3.2.5 on 2022-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0027_auto_20220825_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaotemp',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
