# Generated by Django 3.2.5 on 2021-07-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('fornecedores', '0002_auto_20210708_1133'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='adicional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.banco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='op',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='situacao',
            field=models.CharField(choices=[('ADMITIDO', 'Admitido'), ('DEMITIDO', 'Demitido')], default='ADMITIDO', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_conta',
            field=models.CharField(choices=[('CONTA-CORRENTE', 'Conta-Corrente'), ('POUPANÇA', 'Poupança'), ('CONTA-PAGAMENTO', 'Conta-pagamento')], default='CONTA-CORRENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_pix',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('TELEFONE', 'TELEFONE'), ('EMAIL', 'EMAIL'), ('ALEATÓRIO', 'ALEATÓRIO')], default='CPF', max_length=50),
        ),
    ]
