# Generated by Django 3.2.5 on 2021-07-21 12:02

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210709_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('cargo'), nulls_last=True)]},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('nome'), nulls_last=True)]},
        ),
    ]
