# Generated by Django 4.2.5 on 2023-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionariov2_tipo_demissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariov2',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionariov2',
            name='tipo_demissao',
            field=models.CharField(choices=[('COM JUSTA CAUSA', 'Demissão POR justa causa'), ('SEM JUSTA CAUSA', 'Demissão SEM justa causa'), ('PEDIDO POR JUSTA_CAUSA', 'Pedido de demissão POR justa causa'), ('PEDIDO SEM JUSTA_CAUSA', 'Pedido de demissão SEM justa causa')], default='COM JUSTA CAUSA', max_length=50),
        ),
    ]
