# Generated by Django 4.2.5 on 2024-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_funcionariov2_nome_localdetrabalhofuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariov2',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
