# Generated by Django 3.2.4 on 2021-07-08 08:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PESSOA JURÍDICA', 'Pessoa Jurídica'), ('PESSOA FÍSICA', 'Pessoa Física')], default='PESSOA JURÍDICA', max_length=50)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('inscricao', models.CharField(blank=True, max_length=25, null=True)),
                ('doc', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=30, null=True)),
                ('banco', models.CharField(blank=True, max_length=200, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_conta', models.CharField(choices=[('CONTA-CORRENTE', 'Conta-Corrente'), ('POUPANÇA', 'Poupança'), ('CONTA-PAGAMENTO', 'Conta-pagamento')], default='CONTA-CORRENTE', max_length=50)),
                ('pix', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_pix', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF'), ('TELEFONE', 'TELEFONE'), ('EMAIL', 'EMAIL'), ('ALEATÓRIO', 'ALEATÓRIO')], default='CNPJ', max_length=50)),
                ('faz_nota', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('nome'), nulls_last=True)],
            },
        ),
    ]
