# Generated by Django 3.2.5 on 2023-08-23 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import estoque_v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_auto_20210721_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estoque/', validators=[estoque_v2.models.Ferramenta.validate_image])),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservada', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=False)),
                ('manutencao', models.BooleanField(default=False)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.ForeignKey(blank=True, default='Sem Categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque_v2.categoriaferramenta')),
                ('funcionario_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
            ],
        ),
    ]
