# Generated by Django 3.2.5 on 2023-08-23 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_alter_obra_tipo'),
        ('funcionarios', '0003_auto_20210721_1202'),
        ('estoque_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='data_reserva',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='funcionario_reserva',
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='ReservaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs_entrega', models.CharField(blank=True, max_length=300, null=True)),
                ('obs_devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('almoxarifado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado', to='funcionarios.funcionario')),
                ('ferramenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque_v2.ferramenta')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to='funcionarios.funcionario')),
            ],
        ),
    ]
