# Generated by Django 3.2.5 on 2023-08-24 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20210721_1202'),
        ('obras', '0007_alter_obra_tipo'),
        ('estoque_v2', '0003_auto_20230823_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cautela', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs_entrega', models.CharField(blank=True, max_length=300, null=True)),
                ('obs_devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('almoxarifado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado', to='funcionarios.funcionario')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='CautelaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cautela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautela', to='estoque_v2.cautela')),
                ('ferramenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramenta', to='estoque_v2.ferramenta')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservaFerramenta',
        ),
    ]
