# Generated by Django 3.2.5 on 2023-08-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque_v2', '0004_auto_20230824_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='almoxarifado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
