# Generated by Django 4.2.4 on 2023-09-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0005_alter_cautela_almoxarifado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferramenta',
            old_name='reservada',
            new_name='acautelada',
        ),
    ]
