# Generated by Django 4.2.4 on 2023-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0006_rename_reservada_ferramenta_acautelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='estado',
            field=models.CharField(choices=[('0', 'NOVA'), ('1', 'USADA'), ('2', 'COM DEFEITO')], default='1', max_length=50),
        ),
    ]
