# Generated by Django 4.2.4 on 2023-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0007_cautela_ativa_alter_ferramenta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='situacao',
            field=models.CharField(choices=[('0', 'EM ABERTO'), ('1', 'ATIVA'), ('2', 'ENTREGUE COM OBS'), ('3', 'ENTREGUE')], default='0', max_length=50),
        ),
    ]
