# Generated by Django 4.2.5 on 2024-09-03 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_item_qtd_minima'),
        ('funcionarios', '0011_alter_funcionariov2_nome'),
        ('estoque_v2', '0008_cautela_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('situacao', models.BooleanField(default=True)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante_lista', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='estoque.item')),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista', to='estoque_v2.lista')),
            ],
        ),
    ]
