# Generated by Django 4.2.5 on 2024-09-03 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque_v2', '0009_lista_listaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lista', to=settings.AUTH_USER_MODEL),
        ),
    ]
