# Generated by Django 4.2.5 on 2024-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0010_alter_lista_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='situacao',
        ),
        migrations.AddField(
            model_name='listaitem',
            name='obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listaitem',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
    ]
