# Generated by Django 4.2.5 on 2024-09-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0011_remove_lista_obs_remove_lista_situacao_listaitem_obs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaitem',
            name='qtd_estoque',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listaitem',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='estoque_v2.lista'),
        ),
    ]
