# Generated by Django 4.2.5 on 2024-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_v2', '0012_listaitem_qtd_estoque_alter_listaitem_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaitem',
            name='qtd_requisitada',
            field=models.FloatField(default=0, null=True),
        ),
    ]
