# Generated by Django 3.2.4 on 2021-07-08 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('data_inclusao', models.DateField(blank=True, default='08/07/2021', null=True)),
                ('vencimento', models.DateField(blank=True, default='08/07/2021', null=True)),
                ('pago', models.BooleanField(default=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor')),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.obra')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('vencimento',),
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('data', models.DateField(blank=True, default='08/07/2021', null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor')),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.obra')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('data'), descending=True, nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='valor')),
                ('data', models.DateField(blank=True, default='08/07/2021', null=True)),
                ('total', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.contapagamento')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('data'), descending=True, nulls_last=True)],
            },
        ),
    ]
