# Generated by Django 3.2.4 on 2021-07-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20210715_0838'),
        ('financeiro', '0004_auto_20210715_0908'),
    ]

    operations = [
    ]
