# Generated by Django 3.2.5 on 2021-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_auto_20210827_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='tags',
            field=models.ManyToManyField(blank=True, to='financeiro.TagConta'),
        ),
    ]
