# Generated by Django 3.2.5 on 2022-08-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_auto_20220829_1144'),
        ('financeiro', '0026_auto_20220830_1633'),
    ]

    operations = [
    ]
