# Generated by Django 3.2.5 on 2022-09-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_auto_20220905_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagamento',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='contapagamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='06/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='contapagamento',
            name='vencimento',
            field=models.DateField(blank=True, default='06/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(blank=True, default='06/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data',
            field=models.DateField(blank=True, default='06/09/2022', null=True),
        ),
    ]
