# Generated by Django 3.2.5 on 2022-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0031_auto_20220906_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='acrescimos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='acrescimos'),
        ),
    ]
