# Generated by Django 3.2.5 on 2022-09-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0032_alter_contapagamento_acrescimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='08/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='contapagamento',
            name='vencimento',
            field=models.DateField(blank=True, default='08/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(blank=True, default='08/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data',
            field=models.DateField(blank=True, default='08/09/2022', null=True),
        ),
        migrations.CreateModel(
            name='ItensContaTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('qtd', models.FloatField(blank=True, default=0, null=True)),
                ('unid_medida', models.CharField(choices=[('UNID', 'Unidade'), ('M', 'Metros'), ('M2', 'Metros2'), ('M3', 'Metros3'), ('CX', 'Caixa'), ('CJ', 'Conjunto'), ('PCT', 'Pacote'), ('PÇ', 'Peça'), ('TON', 'Tonelada'), ('L', 'Litros'), ('BD', 'Balde'), ('GL', 'Galão'), ('LT', 'Latão'), ('QTD', 'Quantidade')], default='UNID', max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='valor')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.contapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItensConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('qtd', models.FloatField(blank=True, default=0, null=True)),
                ('unid_medida', models.CharField(choices=[('UNID', 'Unidade'), ('M', 'Metros'), ('M2', 'Metros2'), ('M3', 'Metros3'), ('CX', 'Caixa'), ('CJ', 'Conjunto'), ('PCT', 'Pacote'), ('PÇ', 'Peça'), ('TON', 'Tonelada'), ('L', 'Litros'), ('BD', 'Balde'), ('GL', 'Galão'), ('LT', 'Latão'), ('QTD', 'Quantidade')], default='UNID', max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='valor')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.contapagamento')),
            ],
        ),
    ]
