# Generated by Django 3.2.5 on 2022-09-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0033_auto_20220908_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='valor')),
                ('data', models.DateField(blank=True, default='08/09/2022', null=True)),
                ('total', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.contapagamento')),
            ],
        ),
    ]
