# Generated by Django 3.2.5 on 2022-09-08 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_fiscal'),
        ('fornecedores', '0002_auto_20210708_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0034_pagamentotemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensConta',
            new_name='ItensSaida',
        ),
        migrations.RenameModel(
            old_name='ItensContaTemp',
            new_name='ItensSaidaTemp',
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('nota_fiscal', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor')),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='obras.obra')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='itenssaida',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.saida'),
        ),
        migrations.AlterField(
            model_name='itenssaidatemp',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.saida'),
        ),
    ]
