# Generated by Django 3.2.5 on 2022-09-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_fiscal'),
        ('fornecedores', '0002_auto_20210708_1133'),
        ('financeiro', '0036_alter_saida_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='09/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='contapagamento',
            name='vencimento',
            field=models.DateField(blank=True, default='09/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='itenssaida',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens', to='financeiro.saida'),
        ),
        migrations.AlterField(
            model_name='itenssaidatemp',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='itensTemp', to='financeiro.saida'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(blank=True, default='09/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='pagamentotemp',
            name='data',
            field=models.DateField(blank=True, default='09/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data',
            field=models.DateField(blank=True, default='09/09/2022', null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saidas', to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saidas', to='fornecedores.fornecedor'),
        ),
    ]
