# Generated by Django 3.2.5 on 2022-09-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0038_auto_20220909_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacompleta',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.saida'),
        ),
    ]
