# Generated by Django 3.2.5 on 2022-09-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedores', '0002_auto_20210708_1133'),
        ('obras', '0003_obra_fiscal'),
        ('financeiro', '0039_alter_notacompleta_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacompleta',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacompleta',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacompleta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor'),
        ),
        migrations.CreateModel(
            name='DescricaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saidas', to='obras.obra')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saidas', to='fornecedores.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='itenssaidatemp',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='itensTemp', to='financeiro.descricaonota'),
        ),
        migrations.AlterField(
            model_name='notacompleta',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.descricaonota'),
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
