# Generated by Django 3.2.5 on 2022-09-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0046_auto_20220915_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='obs',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentovista',
            name='obs',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ContaBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField(blank=True)),
                ('doc', models.CharField(blank=True, max_length=25, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.notacompleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
