# Generated by Django 3.2.5 on 2022-09-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0049_contaboleto_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaboleto',
            name='total_parcelas',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
