# Generated by Django 3.2.5 on 2023-08-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0059_auto_20230802_0003'),
        ('financeiro', '0059_auto_20230802_1404'),
    ]

    operations = [
    ]
