# Generated by Django 3.2.5 on 2023-08-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0070_auto_20230821_2037'),
        ('financeiro', '0070_auto_20230823_1428'),
    ]

    operations = [
    ]
