# Generated by Django 4.2.4 on 2023-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0080_alter_contapagamento_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacompleta',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
