# Generated by Django 4.2.5 on 2024-07-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0075_notacompleta_desconto_and_more'),
        ('financeiro', '0081_notacompleta_desconto'),
    ]

    operations = [
    ]
