# Generated by Django 4.2.5 on 2024-07-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0082_merge_20240710_1418'),
        ('financeiro', '0088_alter_contapagamento_data_inclusao_and_more'),
    ]

    operations = [
    ]
