# Generated by Django 4.2.5 on 2024-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0089_merge_20240710_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='03/09/2024', null=True),
        ),
        migrations.AlterField(
            model_name='contapagamento',
            name='vencimento',
            field=models.DateField(blank=True, default='03/09/2024', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(blank=True, default='03/09/2024', null=True),
        ),
        migrations.AlterField(
            model_name='pagamentotemp',
            name='data',
            field=models.DateField(blank=True, default='03/09/2024', null=True),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data',
            field=models.DateField(blank=True, default='03/09/2024', null=True),
        ),
    ]
