# Generated by Django 3.2.5 on 2021-07-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0002_auto_20210708_1133'),
        ('obras', '0001_initial'),
        ('clientes', '0001_initial'),
        ('funcionarios', '0002_auto_20210709_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default='14/07/2021', null=True)),
                ('completo_servico', models.BooleanField(default=False)),
                ('completo_funcionarios', models.BooleanField(default=False)),
                ('completo_itens', models.BooleanField(default=False)),
                ('encarregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('situacao', models.CharField(choices=[('NÃO INICIADO', 'Não Iniciado'), ('EM ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='NÃO INICIADO', max_length=50)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('data_inicio', models.DateField(blank=True, default='14/07/2021', null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('na_planilha', models.BooleanField(default=False)),
                ('ordem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItensServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Quantidade')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.item')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='FotosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='servicos/')),
                ('tipo', models.CharField(choices=[('INICIO', 'Início'), ('DURANTE', 'Durante'), ('FIM', 'Fim')], default='INICIO', max_length=50)),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        
    ]
