# Generated by Django 3.2.5 on 2021-07-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20210708_1133'),
        ('servicos', '0002_auto_20210715_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
    ]
