# Generated by Django 3.2.4 on 2021-07-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20210715_0838'),
        ('servicos', '0003_fornecedorservico'),
    ]

    operations = [
    ]
