# Generated by Django 3.2.5 on 2021-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_merge_0002_auto_20210715_0838_0003_fornecedorservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='16/07/2021', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='16/07/2021', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='situacao',
            field=models.CharField(choices=[('NÃO INICIADO', 'Não Iniciado'), ('EM ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('PENDENTE', 'Pendente'), ('PARALISADO', 'Paralisado')], default='NÃO INICIADO', max_length=50),
        ),
    ]
