# Generated by Django 3.2.5 on 2021-07-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210730_1331'),
        ('servicos', '0007_auto_20210730_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.fiscal'),
        ),
    ]
