# Generated by Django 3.2.5 on 2021-07-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20210721_1202'),
        ('servicos', '0008_alter_ordemservico_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='encarregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
