# Generated by Django 3.2.5 on 2021-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_alter_ordemservico_encarregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='05/08/2021', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='05/08/2021', null=True),
        ),
    ]
