# Generated by Django 3.2.5 on 2021-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_auto_20210811_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='12/08/2021', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='12/08/2021', null=True),
        ),
    ]
