# Generated by Django 3.2.5 on 2021-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0018_auto_20211028_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosservico',
            name='foto',
            field=models.ImageField(height_field='image_height', upload_to='servicos/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='29/10/2021', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='29/10/2021', null=True),
        ),
    ]
