# Generated by Django 3.2.5 on 2021-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0019_auto_20211029_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosservico',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotosservico',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
