# Generated by Django 3.2.5 on 2022-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0026_auto_20220825_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='26/08/2022', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='26/08/2022', null=True),
        ),
    ]
