# Generated by Django 3.2.5 on 2023-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0043_auto_20230605_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='07/06/2023', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='07/06/2023', null=True),
        ),
    ]
