# Generated by Django 3.2.5 on 2023-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0045_auto_20230706_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
