# Generated by Django 3.2.5 on 2023-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0051_merge_0050_auto_20230802_0003_0050_auto_20230802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='03/08/2023', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='03/08/2023', null=True),
        ),
    ]
