# Generated by Django 3.2.5 on 2023-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0062_merge_0061_auto_20230821_2037_0061_auto_20230823_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='23/08/2023', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='23/08/2023', null=True),
        ),
    ]
