# Generated by Django 3.2.5 on 2023-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0064_auto_20230824_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(blank=True, default='30/08/2023', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(blank=True, default='30/08/2023', null=True),
        ),
    ]
