# Generated by Django 3.2.5 on 2021-08-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0003_obra_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, default='11/08/2021', null=True)),
                ('num_medicao', models.IntegerField(blank=True, max_length=20, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor')),
                ('fase', models.CharField(choices=[('-', '-'), ('EMPENHO', 'Empenho'), ('LIQUIDACAO', 'Liquidação'), ('PAGAMENTO', 'Pagamento')], default='-', max_length=50)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, default='11/08/2021', null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor')),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
            ],
        ),
    ]
