# Generated by Django 3.2.5 on 2021-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='num_medicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
