# Generated by Django 3.2.5 on 2021-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_auto_20210811_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturamento',
            old_name='situacao',
            new_name='movimentacao',
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='12/08/2021', null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='fase',
            field=models.CharField(choices=[('-', '-'), ('EMPENHO', 'Empenho'), ('LIQUIDAÇÃO', 'Liquidação'), ('PAGAMENTO', 'Pagamento')], default='-', max_length=50),
        ),
    ]
