# Generated by Django 3.2.5 on 2021-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_auto_20210812_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='num_notafiscal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='13/08/2021', null=True),
        ),
    ]
