# Generated by Django 3.2.5 on 2021-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_alter_faturamento_data_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='27/08/2021', null=True),
        ),
    ]
