# Generated by Django 3.2.5 on 2021-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0010_alter_faturamento_data_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='data_inclusao',
            field=models.DateField(blank=True, default='28/10/2021', null=True),
        ),
    ]
