# Generated by Django 3.2.4 on 2021-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200, unique=True)),
                ('endereco', models.CharField(blank=True, default='Sem endereço', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('objeto', models.TextField(blank=True, max_length=300, null=True)),
                ('endereco', models.CharField(max_length=300)),
                ('contratante', models.CharField(max_length=100)),
                ('num_contrato', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=200)),
                ('fim', models.CharField(max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='preço')),
            ],
        ),
    ]
