# Generated by Django 3.2.5 on 2021-07-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210730_1331'),
        ('obras', '0002_auto_20210716_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.fiscal'),
        ),
    ]
