# Generated by Django 3.2.5 on 2023-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
