# Generated by Django 3.2.5 on 2023-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_auto_20230807_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[(0, 'GERAL'), (1, 'MANUTENÇÃO VIÁRIA'), (2, 'MANUTENÇÃO'), (3, 'PRODUÇÃO'), (4, 'CONSTRUÇÃO')], default=0, max_length=50),
        ),
    ]
