# Generated by Django 3.2.5 on 2021-07-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_auto_20210716_1154'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra'),
        ),
    ]
