# Generated by Django 3.2.5 on 2023-07-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0004_obra_concluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.IntegerField(blank=True, null=True, unique=True)),
                ('solicitante', models.CharField(max_length=200, null=True)),
                ('encarregado', models.CharField(max_length=200, null=True)),
                ('descricao_servico', models.CharField(max_length=200, null=True)),
                ('situacao', models.CharField(choices=[('NÃO INICIADO', 'Não Iniciado'), ('EM ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('PENDENTE', 'Pendente'), ('PARALISADO', 'Paralisado')], default='NÃO INICIADO', max_length=50)),
                ('data_recebimento', models.DateField(blank=True, default='27/07/2023', null=True)),
                ('data_prazo', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('na_planilha', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obra')),
            ],
        ),
    ]
