# Generated by Django 3.2.5 on 2023-07-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0002_auto_20230727_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='28/07/2023', null=True),
        ),
        migrations.CreateModel(
            name='ImagemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='engenharia/')),
                ('OrdemServicoObras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engenharia.ordemservicoobras')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engenharia.categoriaimagem')),
            ],
        ),
    ]
