# Generated by Django 3.2.5 on 2023-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0003_auto_20230728_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemos',
            old_name='OrdemServicoObras',
            new_name='ordem_servico',
        ),
    ]
