# Generated by Django 3.2.5 on 2023-07-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0004_rename_ordemservicoobras_imagemos_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaimagem',
            name='ordem_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engenharia.ordemservicoobras'),
        ),
    ]
