# Generated by Django 3.2.5 on 2023-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0005_categoriaimagem_ordem_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaimagem',
            name='categoria',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
