# Generated by Django 3.2.5 on 2023-08-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0006_alter_categoriaimagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='02/08/2023', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='situacao',
            field=models.CharField(choices=[(0, 'Não Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Paralisado')], default='NÃO INICIADO', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='engenharia/files/')),
                ('nome', models.CharField(max_length=200, null=True, unique=True)),
                ('ordem_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engenharia.ordemservicoobras')),
            ],
        ),
    ]
