# Generated by Django 3.2.5 on 2023-08-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0006_alter_categoriaimagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='02/08/2023', null=True),
        ),
    ]
