# Generated by Django 3.2.5 on 2023-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0007_auto_20230802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoos',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
