# Generated by Django 3.2.5 on 2023-08-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0007_alter_ordemservicoobras_data_recebimento'),
        ('engenharia', '0008_alter_documentoos_nome'),
    ]

    operations = [
    ]
