# Generated by Django 3.2.5 on 2023-08-02 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import engenharia.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engenharia', '0009_merge_20230802_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=engenharia.models.def_pasta_upload),
        ),
        migrations.AlterField(
            model_name='imagemos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=engenharia.models.def_pasta_upload_imagem),
        ),
        migrations.CreateModel(
            name='RegistroOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='02/08/2023')),
                ('registro', models.TextField(max_length=500, null=True)),
                ('ordem_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engenharia.ordemservicoobras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
