# Generated by Django 3.2.5 on 2023-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0012_alter_diariodeobraos_ocorrencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='04/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='04/08/2023', null=True),
        ),
    ]
