# Generated by Django 3.2.5 on 2023-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0015_auto_20230808_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='numero_os',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
