# Generated by Django 3.2.5 on 2023-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0016_alter_ordemservicoobras_numero_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaimagem',
            name='categoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='09/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='09/08/2023', null=True),
        ),
    ]
