# Generated by Django 3.2.5 on 2023-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0017_auto_20230809_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='10/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='10/08/2023', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='situacao',
            field=models.CharField(choices=[(0, 'Não Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Paralisado')], default=0, max_length=50),
        ),
    ]
