# Generated by Django 3.2.5 on 2023-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0018_auto_20230810_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='situacao',
            field=models.CharField(choices=[('0', 'Não Iniciado'), ('1', 'Em andamento'), ('2', 'Pendente'), ('3', 'Paralisado')], default='0', max_length=50),
        ),
    ]
