# Generated by Django 3.2.5 on 2023-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0020_auto_20230811_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='17/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='17/08/2023', null=True),
        ),
    ]
