# Generated by Django 3.2.5 on 2023-08-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0022_auto_20230818_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='21/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='21/08/2023', null=True),
        ),
    ]
