# Generated by Django 3.2.5 on 2023-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0024_merge_0023_auto_20230821_2037_0023_auto_20230823_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='23/08/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='23/08/2023', null=True),
        ),
    ]
