# Generated by Django 4.2.5 on 2024-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0027_auto_20230830_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaimagem',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='10/07/2024'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='10/07/2024', null=True),
        ),
    ]
