# Generated by Django 4.2.5 on 2024-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0028_alter_categoriaimagem_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
