# Generated by Django 4.2.4 on 2023-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0029_alter_diariodeobraos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='04/09/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='04/09/2023', null=True),
        ),
    ]
