# Generated by Django 4.2.5 on 2024-09-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_alter_obra_tipo'),
        ('engenharia', '0030_alter_ordemservicoobras_data_recebimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='11/09/2024', null=True),
        ),
        migrations.CreateModel(
            name='ServiçosDiarioDeObraContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.TextField(blank=True, max_length=500, null=True)),
                ('mao_de_obra', models.TextField(blank=True, max_length=500, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.local')),
            ],
        ),
    ]
