# Generated by Django 4.2.4 on 2023-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0032_alter_diariodeobraos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='08/09/2023'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='08/09/2023', null=True),
        ),
    ]
