# Generated by Django 4.2.5 on 2024-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0037_alter_diariodeobraos_data_and_more_squashed_0038_alter_diariodeobraos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaimagem',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diariodeobraos',
            name='data',
            field=models.DateField(default='28/06/2024'),
        ),
        migrations.AlterField(
            model_name='ordemservicoobras',
            name='data_recebimento',
            field=models.DateField(blank=True, default='28/06/2024', null=True),
        ),
    ]
