# Generated by Django 4.2.5 on 2024-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0038_alter_diariodeobraos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaimagem',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
