# Generated by Django 4.2.5 on 2024-07-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0028_alter_categoriaimagem_categoria_and_more'),
        ('engenharia', '0041_alter_diariodeobraos_data_and_more'),
    ]

    operations = [
    ]
